name: visualizer-ci

on:
  pull_request:
    paths:
      - ".github/workflows/visualizer-ci.yml"
      - "visualizer/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/visualizer-ci.yml"
      - "visualizer/**"

jobs:
  visualizer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: visualizer
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: visualizer/package-lock.json
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
